# Generated by Django 2.2.2 on 2019-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searchdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedata', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'djapp',
            },
        ),
    ]
